package dk.heatless.regex2string.rules;

import dk.heatless.regex2string.Conditions;
import dk.heatless.regex2string.Generator;
import dk.heatless.regex2string.conditions.ValidStringHasBeenGeneratedCondition;

/**
 * A rule that generates a postfix to the string generated for the regular expression.
 */
public class PostfixRule extends Rule {
	
	/**
	 * Constructs a rule that is applicable only if the string generated by the given generator
	 * is a postfix to the complete string generated for the regular expression.<br>
	 * @param generator
	 * generates the postfix.
	 * 
	 * @see
	 * Precondition: {@link Conditions#NO_CONDITION}<br>
	 * Postcondition: {@link Conditions#VALID_STRING_HAS_BEEN_GENERATED}
	 */
	public PostfixRule(Generator generator) {
		super(Conditions.NO_CONDITION, new ValidStringHasBeenGeneratedCondition(), generator);
	}

}
