package dk.heatless.regex2string.rules;

import dk.heatless.regex2string.Conditions;
import dk.heatless.regex2string.Generator;
import dk.heatless.regex2string.Rule;

/**
 * A rule that generates a prefix to the string generated for the regular expression.
 */
public class PrefixRule extends Rule {

	/**
	 * Constructs a rule that is applicable only if the string generated by the given generator
	 * is a prefix to the complete string generated for the regular expression.<br>
	 * @param generator
	 * generates the prefix.
	 * 
	 * @see
	 * Precondition: {@link Conditions#START_OF_GENERATION}<br>
	 * Postcondition: {@link Conditions#NO_CONDITION}
	 */
	public PrefixRule(Generator generator){
		super(	Conditions.START_OF_GENERATION, 
				Conditions.NO_CONDITION, 
				generator);
	}
}
