package dk.heatless.regex2string.generators;

import dk.heatless.regex2string.GenerationState;

/**
 * A simple generator that always generates the same {@code String} or, if the string is not valid, {@code null}.<br>
 */
public class StaticStringGenerator extends VerifiedGenerator {
	
//Fields
	/**
	 * The string to be generated by the instance.
	 */
	private final String toGenerate;

//Constructors
	/**
	 * Constructs generator that always generates the given string.
	 * @param toGenerate
	 */
	public StaticStringGenerator(String toGenerate){
		this.toGenerate = toGenerate;
	}

//Methods
	
	@Override
	protected String generateUnverified(GenerationState state) {
		return this.toGenerate;
	}
	
}
