package dk.heatless.regex2string.core;

/**
 * A simple generator that always generates the same string.
 */
public class StaticStringGenerator implements Generator {
	
//Fields
	/**
	 * The string to be generated by the instance.
	 */
	private final String toGenerate;

//Constructors
	/**
	 * Constructs generator that always generates the given string.
	 * @param toGenerate
	 */
	public StaticStringGenerator(String toGenerate){
		this.toGenerate = toGenerate;
	}

//Methods
	@Override
	public String generate() {
		return this.toGenerate;
	}
	
}
